
project_id = "gylxwukqytuzlcyjutrq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.bkash-payment]
verify_jwt = false

[functions.bkash-callback]
verify_jwt = false
